### PR TITLE
Version 0.26

### PR DESCRIPTION
**Pull request by Cosik**
- changed way that cursor move is calculated
- changed way that sens is set
- added support for changing response delay
- added support for Onshape
- added support for Mouse right button as function key
- celean up some memory usage

### CODE REVIEW

**Comment by Cosik** [comment]
https://www.youtube.com/watch?v=Rv2ZHmy3xk0

**Comment by Cosik** [comment]
Hi @FaqT0tum are you going to review my code or merge it?

**Comment by FaqT0tum** [comment]
Crto, time that I check it and I add it ... thanks for the work

**Comment by FaqT0tum** [comment]
Sure, time that I check it and add it ... thanks for the work

**Comment by ssombra** [comment]
@Cosik I tried your code because I use onshape and it works, thanks. However, after uploading your code I can no longer upload code to my arduino without manually putting the board in bootloader mode (rst + gnd), which is inconvenient as I need to disassemble everything to do it. I tried again with the original FaqT0tum code and it works well, i.e. I can upload code again without the need to manually enter bootloader mode every time. Is there something in your code that generates this issue?

**Comment by Cosik** [comment]
@ssombra no there are only cosmetics changes and one more function. But problem could be when you are i mode other than mouse. Also when you are in menu it should work. Maybe some of keys are not released but they should.

**Comment by ssombra** [comment]
> @ssombra no there are only cosmetics changes and one more function. But problem could be when you are i mode other than mouse. Also when you are in menu it should work. Maybe some of keys are not released but they should.

Maybe is that. Did you have the same issue?
For now I just copied the onshape parts and I have it working, I will try with your code again latter.

**Comment by ssombra** [comment]
I erased the eeprom and upload your code again and I have the same issue. Even in mouse mode and with the menu active, once the Arduino IDE finish compiling and starts uploading the board resets and it wouldn't upload code, it remains in "Uploading status".

**Comment by Cosik** [comment]
Ok, now I remember :D @ssombra do you have connected Orbion directly to PC or over any sort of USB hub? On my side this problem appear only when I'm trying to program it when it is connected to USB hub. When I connect it directly it is working correctly.

**Comment by ssombra** [comment]
> Ok, now I remember :D @ssombra do you have connected Orbion directly to PC or over any sort of USB hub? On my side this problem appear only when I'm trying to program it when it is connected to USB hub. When I connect it directly it is working correctly.

It is directly connected with a USB cable. The issue only appears when your code is on the board, when the original code is on the board I can upload code all the time.

**Comment by FaqT0tum** [comment]
> 

hi, just doing the @cosik changes in the code

**Comment by FaqT0tum** [comment]
Firmware version 0.26 has just been released with the addition of compatibility for Onshape and ANSA. It was also fixed the problem of the keys always pressed when entering the menu.

Thanks a lot @Cosik

-> https://github.com/FaqT0tum/Orbion_Space_Mouse/blob/main/Orbion_Firmware/Orbion_FW_v0.26.ino

**Comment by AFUDIrk** [comment]
Hi there,
I made a few changes that might like one or the other.
Have created a Macrokeyboard.
The encoder holder I have changed in it, which the encoder is bet with the mother.
Thus, the mechanical load does not affect the solder joints.
In addition, I have also designed a bellows (printed from Filaflex), which sits under the encoder holder.
If interest is, I would be allowed to publish it soon.  
Orbion _v1 1_mit_Macroboard

**Comment by Clay2F** [comment]
> Hi there,
> I made a few changes that might like one or the other.
> Have created a Macrokeyboard.
> The encoder holder I have changed in it, which the encoder is bet with the mother.
> Thus, the mechanical load does not affect the solder joints.
> In addition, I have also designed a bellows (printed from Filaflex), which sits under the encoder holder.
> If interest is, I would be allowed to publish it soon.
> Orbion _v1 1_mit_Macroboard

Looks really interesting. 
i would like to see some more details.

**Comment by AFUDIrk** [comment]
Hello, how can I send you the files?  When I reply to your message and add
the files, I get a message that the mail is too large.  But the file is
only 8.7 MB

Mit freundlichen Grüßen
Dirk König

Clay2F ***@***.***> schrieb am Mo., 31. Jan. 2022, 14:05:

**Comment by Clay2F** [comment]
You can upload them in an own repository. 

Gruß Yannick

**Comment by AFUDIrk** [comment]
I have never done that.  Will try that tomorrow.

Mit freundlichen Grüßen
Dirk König

Clay2F ***@***.***> schrieb am Mo., 31. Jan. 2022, 19:07:

**Comment by AFUDIrk** [comment]
I think they forked the responsi.  I have now uploaded my changed files.
and I hope it's right.

Mit freundlichen Grüßen
Dirk König

Clay2F ***@***.***> schrieb am Mo., 31. Jan. 2022, 19:07:

**Pull request closed without merging**
